### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by ahuth** [mavenlink/design-system#3]
- [x] Switch to react-styleguidist
- [ ] Add stylesheet linting
  - Prevent `font-size`
  - Prevent px values for anything
- [x] Fallback to system-ui font if Open Sans isn't present
